export { default as Home } from './Home';
export { default as Login } from './Login';
export { default as Register } from './Register';
export { default as Dashboard } from './Dashboard';
export { default as Employees } from './Employees';
export { default as Buses } from './Buses';
export { default as Fares } from './Fares';
export { default as Reports } from './Reports';
export { default as Schedules } from './Schedules';
